version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: localhost
      DB_USER: postgres
      DB_PASSWORD: secret
      DB_NAME: cloudsuite_hr_db
    volumes:
      - .:/app

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: cloudsuite_hr_db
    ports:
      - "5432:5432"
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    command: ["postgres", "-c", "shared_preload_libraries=uuid-ossp"]

volumes:
  dbdata:
